import AsideLayout from '@/components/AsideLayout'
import '../styles/globals.css'
import "../styles/index.scss"
import { Jost } from 'next/font/google'

const jost = Jost({ subsets: ['latin'] })

export const metadata = {
  title: 'Cats app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <body className={jost.className}>
        <section className='page'>        
          <main className='main'>
            <div className='modal__mask hidden'/>
            <AsideLayout/>
            {children}
          </main>              
        </section>
      </body>
    </html>
  )
}
